# Generated by Django 5.1 on 2024-08-22 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(help_text='name or description of the product', max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(help_text='quantity of the product', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('number', 'Number'), ('litre', 'Litre'), ('mm', 'Millimeter (mm)'), ('cm', 'Centimeter (cm)'), ('in', 'Inch (in)'), ('ft', 'Foot (ft)'), ('mm2', 'Square Millimeter (mm²)'), ('cm2', 'Square Centimeter (cm²)'), ('m2', 'Square Meter (m²)'), ('ft2', 'Square Foot (ft²)')], help_text='unit of measurement', max_length=20)),
            ],
        ),
    ]
