# Generated by Django 5.1 on 2024-08-22 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='previous balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='amount used', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='rate for each', max_digits=10),
        ),
    ]
