# Generated by Django 5.1 on 2024-08-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products_balance_products_expenses_products_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='previous balance', max_digits=10, null=True),
        ),
    ]
