# Generated by Django 5.1 on 2024-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_products_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='previous balance', max_digits=10),
        ),
    ]
